name: Deploy the Gimmedat backend
env:
  CI: false

on:
  push:
    branches:
      - main
    paths-ignore:
      - "build/**"
      - ".github/**"
      - "infra/**"
      - "frontend-vite/**"

  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to "dev" or "prod"'
        required: true
        type: choice
        default: "dev"
        options:
          - "dev"
          - "prod"

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64

      - name: Set environment
        id: environment
        run: |
          ENV_INPUT=${{ inputs.env }}
          DEPLOY_ENVIRONMENT=${ENV_INPUT:-"dev"}
          echo "::set-output name=DEPLOY_ENVIRONMENT::${DEPLOY_ENVIRONMENT}"
          ./build/scripts/accountid.sh ${DEPLOY_ENVIRONMENT}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ steps.environment.outputs.ACCOUNT_ID }}:role/github-service-roles/gimmedat-${{ steps.environment.outputs.DEPLOY_ENVIRONMENT }}-backend-ghaction
          role-session-name: GithubDeployAction
          aws-region: eu-central-1

      - name: Build and deploy API
        run: make backend__deploy_api
      
      - name: Build and deploy dynamoDB stream handler
        run: make backend__deploy_trash_collector

      - name: Build and deploy S3 event handler
        run: make backend__deploy_s3_handler
