name: Deploy the Gimmedat Frontend
env:
  CI: false

on:
  push:
    branches:
      - main
    paths-ignore:
      - "build/**"
      - ".github/**"
      - "infra/**"
      - "backend/**"

  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to "dev" or "prod"'
        required: true
        type: choice
        default: "dev"
        options:
          - "dev"
          - "prod"

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set environment
        id: environment
        run: |
          ENV_INPUT=${{ inputs.env }}
          DEPLOY_ENVIRONMENT=${ENV_INPUT:-"dev"}
          echo "::set-output name=DEPLOY_ENVIRONMENT::${DEPLOY_ENVIRONMENT}"
          ./build/scripts/accountid.sh ${DEPLOY_ENVIRONMENT}
      - name: Build
        run: make frontend__build
        env:
          ENVIRONMENT: ${{ steps.environment.outputs.DEPLOY_ENVIRONMENT }}
          REACT_APP_API_URL: https://ce8gryt0wj.execute-api.eu-central-1.amazonaws.com/dev #temp hardcoded API URL
          VITE_APP_API_URL: https://ce8gryt0wj.execute-api.eu-central-1.amazonaws.com/dev #temp hardcoded API URL
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ steps.environment.outputs.ACCOUNT_ID }}:role/github-service-roles/gimmedat-${{ steps.environment.outputs.DEPLOY_ENVIRONMENT }}-spadeploy-ghaction
          role-session-name: GithubDeployAction
          aws-region: eu-central-1

      - name: Upload to S3
        run: |
          make frontend_vite__deploy
        env:
          AWS_DEFAULT_REGION: "eu-central-1"
          ENVIRONMENT: ${{ steps.environment.outputs.DEPLOY_ENVIRONMENT }}
